version: '3'

services:
  app:
    restart: always
    container_name: Myfarhan
    environment:
      - TZ=Asia/Makassar
    build:
      context: .
    ports:
      - "8007:8007"
    volumes:
      - .:/app
    command: gunicorn myfarhan.wsgi:application --bind 0.0.0.0:8007 --workers 2